### ISSUE TITLE
Documentation of vbguest plugin

### ISSUE THREAD

**Issue by pho3nixf1re** [danielmenezesbr/modernie-winrm#4]
There should be something in the readme about install the vagrant plugin vagrant-vbguest.

`vagrant plugin install vagrant-vbguest`

Took me a few minutes to realize I did not have this yet as the error is simply:

```
$  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
  * Unknown configuration section 'vbguest'.
```

**Comment by danielmenezesbr** [comment]
Thanks @pho3nixf1re!

I updated the documentation with vagrant-vbguest instalation: https://github.com/danielmenezesbr/modernie-winrm#instalation
